"""Pydantic models for the Persome HTTP REST API."""

from __future__ import annotations

import math
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator

from ..security.body_limit import HEALTH_IMPORT_MAX_REQUEST_BODY_BYTES

# Capture payloads contain a rendered AX tree and, optionally, one JPEG.  The
# native producer normally stays well below these limits.  Explicit ceilings
# protect the HTTP process before the payload reaches OCR/encryption/disk.
MAX_CAPTURE_JSON_BYTES = 12 * 1024 * 1024
MAX_CAPTURE_IMAGE_B64_CHARS = 8 * 1024 * 1024
MAX_CAPTURE_METADATA_BYTES = 128 * 1024
MAX_CAPTURE_AX_TREE_BYTES = 8 * 1024 * 1024
MAX_HEALTH_EVENTS_PER_REQUEST = 1000
MAX_HEALTH_METADATA_BYTES = 64 * 1024
MAX_HEALTH_STRING_VALUE_BYTES = 4 * 1024
MAX_MOBILE_EVENT_TEXT_BYTES = 512 * 1024


def _json_size(value: Any) -> int:
    import json

    return len(json.dumps(value, ensure_ascii=False, separators=(",", ":")).encode("utf-8"))


# ─── Generic envelope ──────────────────────────────────────────────────────


class ApiResponse(BaseModel):
    """Common response envelope for the local runtime API."""

    success: bool = Field(default=True, description="Whether the request succeeded")
    data: dict | list | str | None = Field(default=None, description="Response payload")


class ModelPing(BaseModel):
    stage: str = Field(description="LLM stage name, such as timeline, reducer, or classifier")
    model: str = Field(description="Configured model name")
    ok: bool = Field(description="Whether the stage model is reachable")
    latency_ms: int | None = Field(default=None, description="Ping latency in milliseconds")
    error: str | None = Field(default=None, description="Error returned when the ping fails")


class CaptureIngestBody(BaseModel):
    """One capture frame pushed by a trusted Swift producer.

    The Swift process owns Accessibility and Screen Recording permissions and
    supplies the AX tree plus an optional focused-window screenshot. The daemon
    performs enrichment and persistence. Fields align with the native
    ``_build_capture`` output and degrade safely when optional data is absent.
    """

    timestamp: str | None = Field(
        default=None,
        max_length=64,
        description="ISO 8601 capture time; generated by the server when omitted",
    )
    trigger: dict[str, Any] | None = Field(
        default=None,
        description="Trigger metadata: {event_type, bundle_id, window_title, details?}",
    )
    window_meta: dict[str, Any] = Field(
        default_factory=dict, description="{app_name, title, bundle_id}"
    )
    ax_tree: dict[str, Any] | None = Field(
        default=None,
        description="Raw AX tree: {apps -> windows -> elements}; omission means AX is unavailable",
    )
    ax_metadata: dict[str, Any] | None = Field(default=None, description="AX capture metadata")
    screenshot: dict[str, Any] | None = Field(
        default=None,
        description=(
            "{image_base64, mime_type, width, height}; plaintext in transit and encrypted "
            "at rest according to server configuration"
        ),
    )
    ocr_jpeg_b64: str | None = Field(
        default=None,
        max_length=MAX_CAPTURE_IMAGE_B64_CHARS,
        description="Base64 focused-window JPEG for local OCR when AX text is insufficient",
    )
    ocr_tier: str | None = Field(
        default=None,
        max_length=32,
        description="Per-capture OCR tier override; uses configuration when omitted",
    )

    @model_validator(mode="after")
    def _bounded_payload(self) -> CaptureIngestBody:
        for label, value in (
            ("trigger", self.trigger),
            ("window_meta", self.window_meta),
            ("ax_metadata", self.ax_metadata),
        ):
            if value is not None and _json_size(value) > MAX_CAPTURE_METADATA_BYTES:
                raise ValueError(f"{label} exceeds {MAX_CAPTURE_METADATA_BYTES} bytes")

        if self.ax_tree is not None and _json_size(self.ax_tree) > MAX_CAPTURE_AX_TREE_BYTES:
            raise ValueError(f"ax_tree exceeds {MAX_CAPTURE_AX_TREE_BYTES} bytes")

        if self.screenshot is not None:
            image = self.screenshot.get("image_base64")
            if image is not None and (
                not isinstance(image, str) or len(image) > MAX_CAPTURE_IMAGE_B64_CHARS
            ):
                raise ValueError(
                    f"screenshot.image_base64 exceeds {MAX_CAPTURE_IMAGE_B64_CHARS} characters"
                )

        if _json_size(self.model_dump()) > MAX_CAPTURE_JSON_BYTES:
            raise ValueError(f"capture payload exceeds {MAX_CAPTURE_JSON_BYTES} bytes")
        return self


class HealthEventSource(BaseModel):
    """Device/provider identity attached to a health event."""

    provider: str = Field(min_length=1, max_length=64, pattern=r"^[a-z0-9][a-z0-9_-]*$")
    device: str | None = Field(default=None, max_length=160)
    device_id: str | None = Field(default=None, max_length=256)


class HealthEvent(BaseModel):
    """One normalized observation produced by HealthKit or another connector."""

    event_id: str = Field(min_length=1, max_length=512)
    source: HealthEventSource
    metric: str = Field(min_length=1, max_length=96, pattern=r"^[a-z][a-z0-9_.-]*$")
    value: float | str
    unit: str = Field(default="", max_length=32)
    started_at: datetime
    ended_at: datetime | None = None
    timezone: str | None = Field(default=None, max_length=64)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _valid_event(self) -> HealthEvent:
        if self.started_at.tzinfo is None:
            raise ValueError("started_at must include a timezone offset")
        if self.ended_at is not None:
            if self.ended_at.tzinfo is None:
                raise ValueError("ended_at must include a timezone offset")
            if self.ended_at < self.started_at:
                raise ValueError("ended_at must not precede started_at")
        if isinstance(self.value, str) and not self.value.strip():
            raise ValueError("string value must not be empty")
        if (
            isinstance(self.value, str)
            and len(self.value.encode("utf-8")) > MAX_HEALTH_STRING_VALUE_BYTES
        ):
            raise ValueError(f"string value exceeds {MAX_HEALTH_STRING_VALUE_BYTES} bytes")
        if isinstance(self.value, float) and not math.isfinite(self.value):
            raise ValueError("numeric value must be finite")
        if _json_size(self.metadata) > MAX_HEALTH_METADATA_BYTES:
            raise ValueError(f"metadata exceeds {MAX_HEALTH_METADATA_BYTES} bytes")
        return self


class HealthEventDeletion(BaseModel):
    """Provider-scoped deletion receipt emitted by an anchored source query."""

    event_id: str = Field(min_length=1, max_length=512)
    provider: str = Field(min_length=1, max_length=64, pattern=r"^[a-z0-9][a-z0-9_-]*$")


class HealthEventsImportBody(BaseModel):
    """Bounded atomic batch of normalized health changes."""

    schema_version: Literal[1] = 1
    events: list[HealthEvent] = Field(
        default_factory=list, max_length=MAX_HEALTH_EVENTS_PER_REQUEST
    )
    deleted_events: list[HealthEventDeletion] = Field(
        default_factory=list,
        max_length=MAX_HEALTH_EVENTS_PER_REQUEST,
    )

    @model_validator(mode="after")
    def _bounded_batch(self) -> HealthEventsImportBody:
        operation_count = len(self.events) + len(self.deleted_events)
        if operation_count < 1:
            raise ValueError("at least one event or deletion is required")
        if operation_count > MAX_HEALTH_EVENTS_PER_REQUEST:
            raise ValueError(f"batch exceeds {MAX_HEALTH_EVENTS_PER_REQUEST} operations")
        if _json_size(self.model_dump(mode="json")) > HEALTH_IMPORT_MAX_REQUEST_BODY_BYTES:
            raise ValueError(
                f"health import payload exceeds {HEALTH_IMPORT_MAX_REQUEST_BODY_BYTES} bytes"
            )
        return self


class MobileDevice(BaseModel):
    """Stable, non-secret identity attached to a mobile observation."""

    id: str = Field(min_length=1, max_length=128)
    platform: str = Field(pattern="^(ios|android)$")
    name: str | None = Field(default=None, max_length=128)


class MobileEventIngestBody(BaseModel):
    """One owner-initiated observation from a paired Persome companion."""

    schema_version: int = Field(default=1, ge=1, le=1)
    event_id: str = Field(min_length=1, max_length=128)
    captured_at: str | None = Field(default=None, max_length=64)
    device: MobileDevice
    kind: str = Field(
        pattern="^(share|text|url|voice|photo|file|location|usage)$",
        description="How the mobile observation was produced",
    )
    source_app: str | None = Field(default=None, max_length=128)
    title: str | None = Field(default=None, max_length=512)
    text: str | None = Field(default=None)
    url: str | None = Field(default=None, max_length=8192)
    note: str | None = Field(default=None, max_length=4096)
    sensitivity: str = Field(default="private", pattern="^(private|sensitive)$")

    @model_validator(mode="after")
    def _valid_mobile_event(self) -> MobileEventIngestBody:
        if not any((self.title, self.text, self.url, self.note)):
            raise ValueError("mobile event must include title, text, url, or note")
        text_bytes = len((self.text or "").encode("utf-8"))
        if text_bytes > MAX_MOBILE_EVENT_TEXT_BYTES:
            raise ValueError(f"text exceeds {MAX_MOBILE_EVENT_TEXT_BYTES} bytes")
        return self
